### ISSUE TITLE
那須 Chapter1 Plan

### ISSUE THREAD

**Issue by umepon0626** [pj100-team/part-time-tutorial#14]
## Chapter1

このChapterで勉強した内容やCheckPointの答えを下のコメントにメモしていきましょう！

## :cyclone: 作成時のチェック事項

- [x] Assigneeはちゃんと指定されているか
- [x] 何をいつまでにやるかについて関係者が認識できているか

**Comment by umepon0626** [comment]
CheckPointの答えをコメントに書いていく

**Comment by NasuYuto** [comment]
Q1: mkdir tutorial
Q2: touch git-command.txt
Q3: git | grep repository > git-command.txt
Q4: export PATH=$PATH:(追加したいパス今回はhogeの絶対パス)をコマンドに入力することでPATHに設定することができ、hogeだけでコマンドを実行することができるようになる。

**Comment by NasuYuto** [comment]
chap1終わったのでchap2へ進みます。
