### ISSUE TITLE
[武田] Chapter[2] Plan

### ISSUE THREAD

**Issue by umepon0626** [pj100-team/part-time-tutorial#17]
## Chapter[2]

このChapterで勉強した内容やCheckPointの答えを下のコメントにメモしていきましょう！

## :cyclone: 作成時のチェック事項

- [x] Assigneeはちゃんと指定されているか
- [x] 何をいつまでにやるかについて関係者が認識できているか

**Comment by yudai-takeda** [comment]
Chap2のCheckpointの回答を以下に記録しています。
https://github.com/yudai-takeda/tutorial_answer/blob/main/Chap2.md
Chap3に進みます。
