### ISSUE TITLE
質問！ <Chap1[次のChapterを始める前に]について>

### ISSUE THREAD

**Issue by NasuYuto** [pj100-team/part-time-tutorial#20]
## :bug: バグの概要

tutorialリモートリポジトリに修正版であるローカルリポジトリをpushしようとすると、「ERROR: Permission to pj100-team/part-time-tutorial.git denied to NasuYuto.
fatal: Could not read from remote repository.」このようなエラーが出てしまいます、SSHKeyを再登録などしたのですが解決できません。アドバイスをおねがいします。

## :cyclone: バグの再現手順と発生環境
主にsourcetreeでリモートリポジトリの内容を編集し、コマンドなどでcommit→pushしたところ、でエラー。

## :innocent: 期待する動作と実際の動作

pushされた後、PULLリクエストを提出して完了。

## :memo: 調べたこと
SSHkeyが対象のリモートリポジトリに登録されず、アクセス権が得られない？←再度SSHkeyを登録しなおしても同じエラー。

**Comment by umepon0626** [comment]
![スクリーンショット 2023-06-06 13 32 48](https://github.com/pj100-team/part-time-tutorial/assets/43326360/0b448107-3206-40a7-a601-147d8917a11f)
ごめんなさい！正体のときにRead権限しかなかったからっぽいですね:pray:

今権限をwrite権限に修正しましたので、もう一度試してみてください！

@NasuYuto @nishishimakenya

**Comment by NasuYuto** [comment]
ありがとうございます！次回の出勤時試します。
