### ISSUE TITLE
小寺くんChap1

### ISSUE THREAD

**Issue by nijimajohn** [pj100-team/part-time-tutorial#43]
### 追加したいこと

①CheckPointで、下記写真のVScodeのソース管理から、Gitに何かpushするCheckPointがあるといいかも？
（社員さんのプロジェクトではVScodeからGitにプッシュするプロジェクトがあるそうです。）

<img width="62" alt="スクリーンショット 2023-08-09 11 36 29" src="https://github.com/pj100-team/part-time-tutorial/assets/86758487/1dad7525-7445-4158-ace5-eed9a041cd51">
<br />
<br />
<br />
<br />

~~②エディタ説明時に、下記記事みたいなのを参考に、便利な拡張機能について記載しておくと、後々効率的に課題進められそうです。（後のチャプターで既に便利な拡張機能について説明済みなら、ごめんなさい！）
https://zenn.dev/toono_f/articles/38fd6ce1cf82e5~~

**Comment by umepon0626** [comment]
お疲れ様です！確認遅れてしまって申し訳ないです！こちらの変更などPR出していただけないでしょうか？
